/**
 * The attribute allowlist (SPEC 13.3).
 *
 * > The SVG serialiser escapes `& < > " '` in text content and attribute values,
 * > and **rejects attribute names outside a fixed allowlist**.
 *
 * Every attribute this backend emits is generated by `build.ts` from typed scene
 * fields, so in normal operation nothing can reach the emitter that is not on
 * this list. The list is therefore not the primary defence — it is the assertion
 * that the primary defence is still holding. A future node kind that
 * accidentally forwards a document-supplied key trips it immediately, in a unit
 * test, rather than shipping an `onload=` into someone's page.
 *
 * Note what is *absent*: every `on*` handler, `style`, `xlink:href` (the
 * deprecated spelling that older sanitisers forget), `filter`, and `xmlns:xlink`.
 */

const ALLOWED = new Set<string>([
  // Structure and identity
  'class',
  'id',
  'role',
  'tabindex',
  'viewBox',
  'xmlns',
  'preserveAspectRatio',
  'width',
  'height',
  'lang',
  'xml:lang',
  'xml:space',
  'overflow',
  // ARIA
  'aria-activedescendant',
  'aria-describedby',
  'aria-hidden',
  'aria-label',
  'aria-labelledby',
  'aria-live',
  'aria-roledescription',
  // Geometry
  'x',
  'y',
  'x1',
  'y1',
  'x2',
  'y2',
  'cx',
  'cy',
  'r',
  'rx',
  'ry',
  'd',
  'points',
  'transform',
  'gradientTransform',
  'patternTransform',
  'gradientUnits',
  'patternUnits',
  'patternContentUnits',
  'clipPathUnits',
  'offset',
  'href',
  // Paint
  'fill',
  'fill-opacity',
  'fill-rule',
  'stroke',
  'stroke-width',
  'stroke-linecap',
  'stroke-linejoin',
  'stroke-miterlimit',
  'stroke-dasharray',
  'stroke-dashoffset',
  'stroke-opacity',
  'opacity',
  'stop-color',
  'stop-opacity',
  'clip-path',
  'pointer-events',
  'shape-rendering',
  'vector-effect',
  // Text
  'font-family',
  'font-size',
  'font-style',
  'font-weight',
  'letter-spacing',
  'text-anchor',
  'dominant-baseline',
  'font-variant-numeric',
  'font-feature-settings',
  'textLength',
  'lengthAdjust',
  // The backend's own data hooks, consumed by `interaction.ts`
  'data-mdv-region',
  'data-mdv-group',
  'data-mdv-series',
  'data-mdv-datum',
  'data-mdv-mark',
  'data-mdv-kind',
]);

/** `true` when `name` may be emitted. */
export function isAllowedAttribute(name: string): boolean {
  return ALLOWED.has(name);
}

/** The allowlist itself, for tests and for a host that wants to audit it. */
export function allowedAttributes(): readonly string[] {
  return [...ALLOWED].sort();
}

/**
 * Throw for an attribute outside the allowlist.
 *
 * Loud rather than silent: a dropped attribute is a rendering bug that shows up
 * as "the chart looks slightly wrong" three layers away, while a thrown error
 * names the offender at the line that produced it.
 */
export function assertAllowedAttribute(name: string): void {
  if (!ALLOWED.has(name)) {
    throw new Error(
      `@mdv/render-svg refused to emit attribute ${JSON.stringify(name)}: not on the SPEC 13.3 allowlist`,
    );
  }
}
