/**
 * Stable node identifiers.
 *
 * Ids are generated by a monotonic counter rather than a random source so that
 * every engine operation is reproducible: reading the same text twice with a
 * fresh factory yields two byte-identical documents, ids included. That is what
 * makes the round-trip property tests meaningful and what keeps snapshot
 * diffing useful (SPEC 17.3, 24.3 — determinism).
 */

/** Opaque-ish identifier for a document node. Plain string: JSON-safe. */
export type NodeId = string;

/** Allocates the next id in a deterministic sequence. */
export type IdFactory = () => NodeId;

/**
 * Create a deterministic id factory.
 *
 * @param prefix - Namespace for the generated ids. Distinct prefixes let two
 *   documents (e.g. the editor buffer and a clipboard fragment) coexist without
 *   colliding.
 * @param start - First counter value; defaults to 1.
 */
export function createIdFactory(prefix = 'n', start = 1): IdFactory {
  let next = start;
  return () => `${prefix}${next++}`;
}

/**
 * Rewrite every id in a JSON-cloneable node tree using `factory`, in a stable
 * pre-order walk. Used when a fragment is pasted into a document that may
 * already contain its ids.
 *
 * Only the `id` property is rewritten; every other value is copied verbatim.
 */
export function reassignIds<T>(value: T, factory: IdFactory): T {
  if (Array.isArray(value)) {
    return value.map((item) => reassignIds(item, factory)) as unknown as T;
  }
  if (value !== null && typeof value === 'object') {
    const source = value as Record<string, unknown>;
    const out: Record<string, unknown> = {};
    // Preserve key order; assign the new id in place so the walk stays pre-order.
    for (const key of Object.keys(source)) {
      out[key] = key === 'id' && typeof source[key] === 'string' ? factory() : source[key];
    }
    for (const key of Object.keys(out)) {
      if (key !== 'id') out[key] = reassignIds(out[key], factory);
    }
    return out as unknown as T;
  }
  return value;
}
